Repository openhab/openhab-distro, pull requests merged in 2021-12, with the labels that each got.

#1342 Resolve runbundles for Whiteboard downgrade
  launch/app/app.bndrun
Labels: awaiting other PR

#1343 Mitigate potential Remote-Code-Execution caused by CVE-2021-44228
  distributions/openhab/src/main/resources/bin/setenv
  distributions/openhab/src/main/resources/bin/setenv.bat
Labels: bug

#1344 Upgrade to Karaf 4.3.4
  distributions/openhab/src/main/filtered-resources/userdata/etc/org.apache.karaf.features.cfg
  distributions/openhab/src/main/resources/bin/karaf
  distributions/openhab/src/main/resources/bin/karaf.bat
  distributions/openhab/src/main/resources/bin/setenv
  distributions/openhab/src/main/resources/bin/setenv.bat
  launch/app/app.bndrun
  pom.xml
Labels: enhancement, karaf, awaiting other PR, security
