Repository openhab/openhab-distro, pull requests merged in 2023-03, with the labels that each got.

#1446 Upgrade to Karaf 4.4.3
  distributions/openhab/src/main/resources/bin/karaf
  distributions/openhab/src/main/resources/bin/karaf.bat
  distributions/openhab/src/main/resources/bin/setenv
  distributions/openhab/src/main/resources/bin/setenv.bat
  distributions/openhab/src/main/resources/runtime/etc/jetty.xml
  distributions/openhab/src/main/resources/userdata/etc/org.apache.karaf.shell.cfg
  launch/app/app.bndrun
  pom.xml
Labels: enhancement, karaf

#1460 Enable GZIP compression for Jetty webserver
  distributions/openhab/src/main/resources/runtime/etc/jetty.xml
Labels: enhancement

#1483 [knx] Add breaking change alert (UoM)
  distributions/openhab/src/main/resources/bin/update.lst
Labels: awaiting other PR
