Repository openhab/openhab-distro, pull requests merged in 2025-01, with the labels that each got.

#1716 Upgrade plugins
  distributions/openhab/pom.xml
  launch/app/pom.xml
  pom.xml
Labels: infrastructure

#1720 Resolve app.bndrun runbundles for Jollyday upgrade
  launch/app/app.bndrun
Labels: awaiting other PR

#1721 Fix dependencies of app
  launch/app/app.bndrun
Labels: bug, regression
